version: 1.0.{build}

branches:
  only:
    - master
    - 0.20.x

environment:
  matrix:
    - os: Visual Studio 2013
      GENERATOR_NAME: "Visual Studio 12 2013"
    - os: Visual Studio 2015
      GENERATOR_NAME: "Visual Studio 14 2015"
# TODO: Uncomment when AppVeyor will provide XP toolchain for VS2017
#    - os: Visual Studio 2017
#      GENERATOR_NAME: "Visual Studio 15 2017"

clone_folder: c:\projects\xash\xash3d

build:
  project: INSTALL.vcxproj
  verbosity: normal

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive
  - cmake -G "%GENERATOR_NAME%" c:\projects\xash\xash3d

after_build:
  # Create archive
  - 7z a -t7z xash3d-win.7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on c:\projects\xash\xash3d\%CONFIGURATION%
  - appveyor PushArtifact xash3d-win.7z
  - curl --upload-file xash3d-win.7z https://transfer.sh/xash3d-win.7z
