# DO NOT DELETE

pe_resource.o: wine/pshpack1.h wine/poppack.h wine/pshpack2.h wine/winbase.h
pe_resource.o: wine/basetsd.h wine/winestring.h wine/module.h wine/pe_image.h
pe_resource.o: wine/heap.h wine/debugtools.h ext.h
resource.o: wine/windef.h wine/pshpack1.h wine/poppack.h wine/pshpack2.h
resource.o: wine/winestring.h wine/windef.h wine/winuser.h wine/heap.h
resource.o: wine/winbase.h wine/module.h wine/pe_image.h wine/debugtools.h
resource.o: wine/winerror.h loader.h wine/driver.h wine/mmreg.h wine/vfw.h
resource.o: wine/msacm.h wine/driver.h wine/mmreg.h
registry.o: wine/pshpack2.h wine/winestring.h wine/winreg.h wine/winbase.h
registry.o: wine/winnt.h wine/winerror.h ext.h wine/windef.h registry.h
loader.o: config.h wine/winnt.h wine/windef.h wine/pshpack1.h wine/poppack.h
loader.o: wine/pshpack2.h wine/winestring.h
ext.o: wine/winbase.h wine/basetsd.h wine/winnt.h wine/windef.h
ext.o: wine/pshpack1.h wine/poppack.h wine/pshpack2.h wine/winestring.h
ext.o: wine/debugtools.h wine/heap.h wine/winbase.h ext.h
module.o: wine/winbase.h wine/basetsd.h wine/winnt.h wine/windef.h
module.o: wine/pshpack1.h wine/poppack.h wine/pshpack2.h wine/winestring.h
module.o: wine/module.h wine/pe_image.h wine/pe_image.h wine/debugtools.h
module.o: win32.h wine/winbase.h com.h
elfdll.o: config.h
win32.o: config.h mangle.h wine/winbase.h wine/basetsd.h wine/winnt.h
win32.o: wine/pshpack2.h wine/winestring.h wine/winreg.h wine/winbase.h
win32.o: wine/winnt.h wine/winerror.h wine/debugtools.h wine/module.h
win32.o: wine/driver.h wine/mmreg.h wine/vfw.h wine/msacm.h wine/driver.h
pe_image.o: wine/basetsd.h wine/winnt.h wine/windef.h wine/pshpack1.h
pe_image.o: wine/poppack.h wine/pshpack2.h wine/winestring.h wine/winerror.h
pe_image.o: wine/heap.h wine/winbase.h wine/pe_image.h wine/module.h
pe_image.o: wine/pe_image.h wine/debugtools.h ext.h win32.h com.h
vfl.o: wine/basetsd.h wine/winnt.h wine/windef.h wine/pshpack1.h
vfl.o: wine/poppack.h wine/pshpack2.h wine/winestring.h com.h
vfl.o: wine/mmreg.h wine/vfw.h wine/msacm.h wine/driver.h wine/mmreg.h
vfl.o: wine/module.h wine/pe_image.h wine/winuser.h wine/winestring.h
