# DO NOT DELETE

vgui_clip.o: ../engine/client/vgui/vgui_api.h ../engine/common/system.h
vgui_clip.o: /usr/include/setjmp.h /usr/include/features.h
vgui_clip.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
vgui_clip.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
vgui_clip.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
vgui_clip.o: /usr/include/stdio.h /usr/include/bits/types.h
vgui_clip.o: /usr/include/bits/typesizes.h /usr/include/libio.h
vgui_clip.o: /usr/include/_G_config.h /usr/include/wchar.h
vgui_clip.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
vgui_clip.o: /usr/include/time.h /usr/include/bits/time.h
vgui_clip.o: /usr/include/xlocale.h ../common/const.h ../common/wrect.h
vgui_int.o: vgui_main.h ../engine/common/system.h /usr/include/setjmp.h
vgui_int.o: /usr/include/features.h /usr/include/stdc-predef.h
vgui_int.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
vgui_int.o: /usr/include/gnu/stubs.h /usr/include/bits/setjmp.h
vgui_int.o: /usr/include/bits/sigset.h /usr/include/stdio.h
vgui_int.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
vgui_int.o: /usr/include/libio.h /usr/include/_G_config.h
vgui_int.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
vgui_int.o: /usr/include/bits/sys_errlist.h /usr/include/time.h
vgui_int.o: /usr/include/bits/time.h /usr/include/xlocale.h ../common/const.h
vgui_int.o: ../engine/client/vgui/vgui_api.h utlvector.h
vgui_int.o: /usr/include/string.h utlmemory.h utlrbtree.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI.h
vgui_int.o: /usr/include/sys/types.h /usr/include/endian.h
vgui_int.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
vgui_int.o: /usr/include/bits/byteswap-16.h /usr/include/sys/select.h
vgui_int.o: /usr/include/bits/select.h /usr/include/sys/sysmacros.h
vgui_int.o: /usr/include/bits/pthreadtypes.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_App.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_MouseCode.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_KeyCode.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Dar.h
vgui_int.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
vgui_int.o: /usr/include/bits/waitstatus.h /usr/include/alloca.h
vgui_int.o: /usr/include/bits/stdlib-float.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Cursor.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Font.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Panel.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Scheme.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Color.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_RepaintSignal.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_SurfaceBase.h
vgui_int.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_InputSignal.h
vgui_input.o: vgui_main.h ../engine/common/system.h /usr/include/setjmp.h
vgui_input.o: /usr/include/features.h /usr/include/stdc-predef.h
vgui_input.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
vgui_input.o: /usr/include/gnu/stubs.h /usr/include/bits/setjmp.h
vgui_input.o: /usr/include/bits/sigset.h /usr/include/stdio.h
vgui_input.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
vgui_input.o: /usr/include/libio.h /usr/include/_G_config.h
vgui_input.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
vgui_input.o: /usr/include/bits/sys_errlist.h /usr/include/time.h
vgui_input.o: /usr/include/bits/time.h /usr/include/xlocale.h
vgui_input.o: ../common/const.h ../engine/client/vgui/vgui_api.h utlvector.h
vgui_input.o: /usr/include/string.h utlmemory.h utlrbtree.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI.h
vgui_input.o: /usr/include/sys/types.h /usr/include/endian.h
vgui_input.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
vgui_input.o: /usr/include/bits/byteswap-16.h /usr/include/sys/select.h
vgui_input.o: /usr/include/bits/select.h /usr/include/sys/sysmacros.h
vgui_input.o: /usr/include/bits/pthreadtypes.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_App.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_MouseCode.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_KeyCode.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Dar.h
vgui_input.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
vgui_input.o: /usr/include/bits/waitstatus.h /usr/include/alloca.h
vgui_input.o: /usr/include/bits/stdlib-float.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Cursor.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Font.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Panel.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Scheme.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Color.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_RepaintSignal.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_SurfaceBase.h
vgui_input.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_InputSignal.h
vgui_input.o: ../engine/common/input.h ../engine/keydefs.h
vgui_surf.o: /usr/include/ctype.h /usr/include/features.h
vgui_surf.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
vgui_surf.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
vgui_surf.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
vgui_surf.o: /usr/include/endian.h /usr/include/bits/endian.h
vgui_surf.o: /usr/include/bits/byteswap.h /usr/include/bits/byteswap-16.h
vgui_surf.o: /usr/include/xlocale.h vgui_main.h ../engine/common/system.h
vgui_surf.o: /usr/include/setjmp.h /usr/include/bits/setjmp.h
vgui_surf.o: /usr/include/bits/sigset.h /usr/include/stdio.h
vgui_surf.o: /usr/include/libio.h /usr/include/_G_config.h
vgui_surf.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
vgui_surf.o: /usr/include/bits/sys_errlist.h /usr/include/time.h
vgui_surf.o: /usr/include/bits/time.h ../common/const.h
vgui_surf.o: ../engine/client/vgui/vgui_api.h utlvector.h
vgui_surf.o: /usr/include/string.h utlmemory.h utlrbtree.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI.h
vgui_surf.o: /usr/include/sys/types.h /usr/include/sys/select.h
vgui_surf.o: /usr/include/bits/select.h /usr/include/sys/sysmacros.h
vgui_surf.o: /usr/include/bits/pthreadtypes.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_App.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_MouseCode.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_KeyCode.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Dar.h
vgui_surf.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
vgui_surf.o: /usr/include/bits/waitstatus.h /usr/include/alloca.h
vgui_surf.o: /usr/include/bits/stdlib-float.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Cursor.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Font.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Panel.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Scheme.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Color.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_RepaintSignal.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_SurfaceBase.h
vgui_surf.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_InputSignal.h
vgui_font.o: vgui_main.h ../engine/common/system.h /usr/include/setjmp.h
vgui_font.o: /usr/include/features.h /usr/include/stdc-predef.h
vgui_font.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
vgui_font.o: /usr/include/gnu/stubs.h /usr/include/bits/setjmp.h
vgui_font.o: /usr/include/bits/sigset.h /usr/include/stdio.h
vgui_font.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
vgui_font.o: /usr/include/libio.h /usr/include/_G_config.h
vgui_font.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
vgui_font.o: /usr/include/bits/sys_errlist.h /usr/include/time.h
vgui_font.o: /usr/include/bits/time.h /usr/include/xlocale.h
vgui_font.o: ../common/const.h ../engine/client/vgui/vgui_api.h utlvector.h
vgui_font.o: /usr/include/string.h utlmemory.h utlrbtree.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI.h
vgui_font.o: /usr/include/sys/types.h /usr/include/endian.h
vgui_font.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
vgui_font.o: /usr/include/bits/byteswap-16.h /usr/include/sys/select.h
vgui_font.o: /usr/include/bits/select.h /usr/include/sys/sysmacros.h
vgui_font.o: /usr/include/bits/pthreadtypes.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_App.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_MouseCode.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_KeyCode.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Dar.h
vgui_font.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
vgui_font.o: /usr/include/bits/waitstatus.h /usr/include/alloca.h
vgui_font.o: /usr/include/bits/stdlib-float.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Cursor.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Font.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Panel.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Scheme.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_Color.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_RepaintSignal.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_SurfaceBase.h
vgui_font.o: /mnt/data/xash/bin/halflife/utils/vgui/include/VGUI_InputSignal.h
